name: ride-sharing-app

services:
  backend:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./ride-sharing-backend/Dockerfile

  frontend:
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: ./ride-sharing-frontend/Dockerfile

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
