package hu.ridesharing.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "journey_passenger", uniqueConstraints = {
        @UniqueConstraint(columnNames = {"journey_id", "passenger_id"})
})
@Getter
@Setter
public class JourneyPassenger {

    /**
     * We are using a manually set uuid here, that is generated by Java's UUID generator implementation.
     */
    @Id
    private String acceptToken;

    @ManyToOne
    @JoinColumn(name = "journey_id")
    private Journey journey;

    @ManyToOne
    @JoinColumn(name = "passenger_id")
    private Passenger passenger;

    private boolean accepted = false;
}
